---
apiVersion: v1
kind: Service
metadata:
  name: app-lb
  namespace: spring-k8s-probes-demo
spec:
  type: NodePort
  ports:
    - port: 80
      protocol: TCP
      targetPort: 8080
  selector:
    role: app
